### ISSUE TITLE
Error with Generating JWT token in the AuthManager class

### ISSUE THREAD

**Issue by lekea4** [trevoirwilliams/HotelListing-API-dotnet5#2]
Good day @trevoirwilliams ,

I have been following your tutorial and I got stuck at this point as I am getting this error while creating the helper method "GenerateTokenOptions" for the method "CreateToken" and the error is as follows;
_**"The best overload for 'JwtSecurityToken' does not have a parameter named 'issuer'"**_ and I can not seem to get past this part of the tutorial.

![JWT-error](https://user-images.githubusercontent.com/67796188/137363404-9dc3a4ed-64ee-4470-b383-81a8f5d85200.jpg)

**Comment by trevoirwilliams** [comment]
Hello @lekea4 ,

This might be because of the library that you are using.
Remove the library reference for that function and use CTRL + . to get the suggestions. Ensure that you are using using `Microsoft.IdentityModel.Tokens; `

**Comment by lekea4** [comment]
Hello @trevoirwilliams,

I am actually using the right library reference, and I have tried to crosscheck with your source code

![image](https://user-images.githubusercontent.com/67796188/137368288-c76b6db9-b380-4735-bc34-0b6f99f08f5d.png)

**Comment by trevoirwilliams** [comment]
Can you share the project here i can take a look?

**Comment by lekea4** [comment]
I am sorry I took this long to respond, was trying to catch the bus on this side of the world


so here is the link to my own :
https://github.com/lekea4/EventCenter

### Key differences

1. The entities are different as **Hotel** is synonymous is **EventPlace** and **Location** is synonymous to **Country** in your code 
2. I Implement the code with clean architecture with multi-layers for strict separation of concerns which is similar to how you also separated the concerns.


I think those are the two main differences, every other implementation is pretty much the same

**Comment by PetkovskiM** [comment]
Hello @trevoirwilliams  @lekea4 ,
I had problems with generating token until i put my key in appsettings.json.
I dont know why i was getting this in my logger " System.ArgumentOutOfRangeException: IDX10653: The encryption algorithm 'System.String' requires a key size of at least 'System.Int32' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 'System.Int32'. (Parameter 'key')".
I tried with my own key,than i set guid as variable in the system environment and the result was same i was still geting error. At the end i put guid in appsettings.json and inserted this two lines in my GetSigninCredetials ( ):
 var jwtSettings = _configuration.GetSection("Jwt");
 var key = jwtSettings.GetSection("KEY").Value;
and solved my problems.
I hope this will help.

**Comment by trevoirwilliams** [comment]
Noted Petkovski. At the end if the day, you just need to ensure that you have a key somewhere you can access it. 

You can always gauge the risk of having it in the appsettings as that exposes it to anyone who might see the code. 

Environment variables, or even appsecrets are also good places to place it.

**Comment by PetkovskiM** [comment]
@trevoirwilliams 
Thanks for the reply, Mr. Williams. Have a great day.
