### ISSUE TITLE
How can I use GetAll with order by

### ISSUE THREAD

**Issue by temesgenmhr** [trevoirwilliams/HotelListing-API-dotnet5#3]
First, thank you for your great work, 

when I trace your code I didn't see a place that references GetAll generic repository, could you assist me please how can I use specifically order by expression, thank you!

**Comment by trevoirwilliams** [comment]
Hello,
The order by is really a lambda expression. So similar to how you specified the where clause as a parameter, you would specify 
`q => q.OrderBy(x => x.ColumnName)`
